language: node_js
cache:
  directories:
  - node_modules
node_js:
- lts/*
before_install:
- git fetch --unshallow
- npm install -g semistandard
- npm install -g prettier
- npm install -g eslint
script:
- npm run linter
- npm run builder
# - npm run packager
# - npm run test
- npm run vscoder
after_success:
- chmod +x .travis/push.sh
- .travis/push.sh
